lost_socks/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'lost_socks.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('main.urls',namespace='main')),
)

main/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'freelancer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'main.views.main',name='main'),
    url(r'^check_activation$', 'main.views.check_activation',name='check_activation'),
    url(r'^report$', 'main.views.report',name='report'),
    url(r'^activate$', 'main.views.activate',name='activate'),
    url(r'^message$', 'main.views.message',name='message'),


    # url(r'^category/(?P<category_id>.+)$', 'main.views.category',name='category'),
    # url(r'^brand/(?P<brand_id>.+)$', 'main.views.brand',name='brand'),
    # url(r'^model/(?P<model_id>.+)$', 'main.views.model',name='model'),
    # url(r'^instance/(?P<instance_id>.+)$', 'main.views.instance',name='instance'),
    # url(r'^add_instance/phones$', 'main.views.add_instance_phones',name='add_instance_phones'),
    # url(r'^add_instance/notebooks$', 'main.views.add_instance_notebooks',name='add_instance_notebooks'),    
    #url(r'^signin$', 'main.views.signin',name='signin'),
    #url(r'^signup$', 'main.views.signup',name='signup'),
    #url(r'^signout$', 'main.views.signout',name='signout'),
)

main/models.py
from django.db import models
from datetime import datetime 
from django.contrib.auth.models import User

class Cardstick(models.Model):
	""" Card info """

	card_id = models.CharField(max_length = 7, unique=True)
	activated = models.BooleanField(default = False)
	telephone = models.CharField(max_length = 20,default = "",null=True, blank=True)
	email = models.CharField(max_length = 50,default = "",null=True, blank=True)
	name = models.CharField(max_length = 100,default = "",null=True, blank=True)

	def __unicode__(self):
		return self.card_id

	class Meta:
		verbose_name = "Карта"
		verbose_name_plural = "Карты"

class Mail(models.Model):
	name = models.CharField('имя отправителя',max_length=100,default = "",null=True, blank=True)
	email = models.CharField(max_length=100,default = "",null=True, blank=True)
	title = models.CharField('тема',max_length=100,default = "",null=True, blank=True)
	body = models.CharField('сообщение',max_length=1000,default = "",null=True, blank=True)
	date = models.DateTimeField('дата отправления', default=datetime.now)
	def __unicode__(self):
		return self.title

	class Meta:
		verbose_name = "сообщение"
		verbose_name_plural = "сообщения"

main/views.py
#importings
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Cardstick, Mail
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
#impoer of models 

def main(request):
	#initialize variables
	args={}
	args.update(csrf(request))
	return render_to_response('main/main.html',args)

def check_activation(request):
	#initialize variables
	args={}
	args.update(csrf(request))
	if request.POST:
		card_id = request.POST['idcode']
		card = Cardstick.objects.filter(card_id = card_id)
		if card.count() > 0:
			card = card[0]
			if card.activated == True:
				message = "Данная карта уже использована, попробуйте еще раз ..."
				args['message'] = message
				return render_to_response('main/check_activation.html',args)
			else:
				args['card_id'] = card.card_id
				message = "Пожалуйста завершите активацию карты."
				args['message'] = message
				return render_to_response('main/activate.html', args)
		else:
			message = "Данный код не действителен, попробуйте еще раз ..."
			args['message'] = message
			return render_to_response('main/check_activation.html',args)
	else:
		return redirect(reverse('main:main'))
	

def report(request):
	#initialize variables
	args={}
	args.update(csrf(request))
	if request.POST:
		card_id = request.POST['card_id']
		card = Cardstick.objects.filter(card_id = card_id)
		if card.count() > 0:
			card = card[0]
			if card.activated == True:
				message = "Пожалуйста свяжитесь с владельцем"
				info = Cardstick.objects.get(card_id = card_id)
				args['info'] = info
			else:
				message = "Данная карта еще не активирована"
		else:
			message = "Данный код не действителен, попробуйте еще раз ..."
		args['message'] = message
		return render_to_response('main/report.html',args)

	else:
		return redirect(reverse('main:main'))

def activate(request):
	#initialize variables
	args={}
	args.update(csrf(request))
	if request.POST:
		name = request.POST['name']
		email = request.POST['email']
		telephone = request.POST['telephone']
		card_id = request.POST['card_id']
		card = Cardstick.objects.get(card_id = card_id)
		card.name = name
		card.email = email
		card.telephone = telephone
		card.activated = True
		
		card.save()
		args["message"] = "Вы успешно активировали идентификатор. "

		return render_to_response('main/thanks_page.html', args)
	else:
		message = "Пожалуйста завершите активацию карты."
		args['message'] = message

	return render_to_response('main/activate.html',args)

def message(request):
	#initialize variables
	args={}
	args.update(csrf(request))
	if request.POST:
		name = request.POST['name']
		email = request.POST['email']
		subject = request.POST['subject']
		message = request.POST['message']
		mail = Mail.objects.create(name=name,email=email,title=subject,body=message)
		mail.save()
	return redirect(reverse('main:main'))

main/templates/main/activate.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>iLost.Kg</title>
	<!-- core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css'%}'%}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/animate.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/owl.carousel.css'%}" rel="stylesheet">
    <link href="{% static 'css/owl.transitions.css'%}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css'%}" rel="stylesheet">
    <link href="{% static 'css/main.css'%}" rel="stylesheet">
    <link href="{% static 'css/responsive.css'%}" rel="stylesheet">



   
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">


</head><!--/head-->
<body id="home" class="homepage">


    <header class="navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <!-- responsive nav button -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- /responsive nav button -->
                    
                    <!-- logo -->
                    <div>
                        <a href="{% url 'main:main'%}" >
                            <h4 style="color:white; font-size:24px;"><span style="color:red">i</span>Lost.Kg</h4>
                        </a>
                    </div>
                    <!-- /logo -->
                </div>

                <!-- main nav -->
                <nav class="collapse navbar-collapse navbar-right" role="navigation">
                    <div >
                        <ul id="nav" class="nav navbar-nav">
                            <li class="scroll"><a href="{%url 'main:main'%}#about" data-section="#about">О нас</a></li>
                            <li class="scroll"><a href="{%url 'main:main'%}#portfolio" data-section="#portfolio">Как это работает</a></li>
                            <li class="scroll"><a href="{%url 'main:main'%}#contact-area" data-section="#contact-area">Обратная связь</a></li>   
                        </ul>
                    </div>
                </nav>
                <!-- /main nav -->
            
                
            </div>
        </header>
    <section id="about">
        <div class="container">
            <div class="row">
                <div class="section-header">
                    <h2 class="section-title text-center wow fadeInDown animated" style="visibility: visible;">{{message}}</h2>
                    <p class="text-center wow fadeInDown animated" style="visibility: visible;">Пожалуйста заполните все поля .</p>
                </div>
                <form name="contact-form" method="post" action="{% url 'main:activate' %}">
                {% csrf_token %}
                    <div class="col-lg-3"></div>
                    <div class="col-lg-6 animated animate-from-left" style="opacity: 1; left: 0px;">

                        <div class="form-group">
                                <label for="name">Ф.И.О</label>
                                <input id="name" type="text" name="name" class="form-control" placeholder="Ариет Нышанбаев" required>
                            </div>
                        <div class="form-group">
                                <label for="email">Email адрес</label>
                                <input type="email" id="email" name="email" class="form-control" placeholder="kira.1sp@gmail.com" required>
                            </div>
                        <div class="form-group">
                            <label for="subject">Номер телефона</label>
                            <input type="text" id="subject" name="telephone" class="form-control" placeholder="0556606737" required>
                        </div>
                        <input type="hidden" value="{{card_id}}" name="card_id" required>
                        
                        <br>
                        <div class="text-center">
                              <button type="submit" class="form-control btn btn-primary btn-lg ">Активировать</button>
                        </div>


                    </div>
                    

                </form>

            </div>
        </div>
    </section><!--/#about-->

    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <p class="text-center">
                        &copy; 2015 iLost.kg </a>
                    </p>
                    <p style="display:none">
                        Ari and JZ)
                    </p>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/mousescroll.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/jquery.isotope.min.js' %}"></script>
    <script src="{% static 'js/jquery.inview.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

main/templates/main/check_activation.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>iLost.Kg</title>
	<!-- core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css'%}'%}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/animate.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/owl.carousel.css'%}" rel="stylesheet">
    <link href="{% static 'css/owl.transitions.css'%}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css'%}" rel="stylesheet">
    <link href="{% static 'css/main.css'%}" rel="stylesheet">
    <link href="{% static 'css/responsive.css'%}" rel="stylesheet">



   
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">


</head><!--/head-->
<body id="home" class="homepage">


    <header class="navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <!-- responsive nav button -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- /responsive nav button -->
                
                <!-- logo -->
                    <div>
                        <a href="{% url 'main:main'%}" >
                            <h4 style="color:white; font-size:24px;"><span style="color:red">i</span>Lost.Kg</h4>
                        </a>
                    </div>
                    <!-- /logo -->
            </div>

            <!-- main nav -->
                <nav class="collapse navbar-collapse navbar-right" role="navigation">
                    <div >
                        <ul id="nav" class="nav navbar-nav">
                            <li class="scroll"><a href="{%url 'main:main'%}#about" data-section="#about">О нас</a></li>
                            <li class="scroll"><a href="{%url 'main:main'%}#portfolio" data-section="#portfolio">Как это работает</a></li>
                            <li class="scroll"><a href="{%url 'main:main'%}#contact-area" data-section="#contact-area">Обратная связь</a></li>   
                        </ul>
                    </div>
                </nav>
                <!-- /main nav -->
            
        </div>
    </header>
   
    

    <section id="about">
        <div class="container">

            <div class="row">
                <div class="col-sm-6 wow fadeInRight">
                <br><br><br><br><br>
                <div class="alert alert-danger alert-dismissible fade in" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                  <h3 class="column-title">{{message}}</h3>
                  <p>
                    <a href="{% url 'main:main'%}"><button type="button" class="btn btn-default">Попробовать заново</button></a>
                  </p>
                </div>
                    
                </div>
                <div class="col-sm-6 wow fadeInLeft">
                    <img class="img-responsive" src="{% static 'images/i_do_not_know.png' %}" alt="">
                </div>
            </div>
        </div>
    </section><!--/#about-->

    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                   <p class="text-center">
                        &copy; 2015 iLost.kg </a>
                    </p>
                    <p style="display:none">
                        Ari and JZ)
                    </p>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/mousescroll.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/jquery.isotope.min.js' %}"></script>
    <script src="{% static 'js/jquery.inview.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>


</body>
</html>

main/templates/main/report.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>iLost.Kg</title>
	<!-- core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css'%}'%}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/animate.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/owl.carousel.css'%}" rel="stylesheet">
    <link href="{% static 'css/owl.transitions.css'%}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css'%}" rel="stylesheet">
    <link href="{% static 'css/main.css'%}" rel="stylesheet">
    <link href="{% static 'css/responsive.css'%}" rel="stylesheet">



   
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">


</head><!--/head-->
<body id="home" class="homepage">


    <header id="top-header" class="navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <!-- responsive nav button -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- /responsive nav button -->
                    
                    <!-- logo -->
                    <div>
                        <a href="{% url 'main:main'%}" >
                            <h4 style="color:white; font-size:24px;"><span style="color:red">i</span>Lost.Kg</h4>
                        </a>
                    </div>
                    <!-- /logo -->
                </div>

               <!-- main nav -->
                <nav class="collapse navbar-collapse navbar-right" role="navigation">
                    <div >
                        <ul id="nav" class="nav navbar-nav">
                            <li class="scroll"><a href="{%url 'main:main'%}#about" data-section="#about">О нас</a></li>
                            <li class="scroll"><a href="{%url 'main:main'%}#portfolio" data-section="#portfolio">Как это работает</a></li>
                            <li class="scroll"><a href="{%url 'main:main'%}#contact-area" data-section="#contact-area">Обратная связь</a></li>   
                        </ul>
                    </div>
                </nav>
                <!-- /main nav -->
            
                
            </div>
        </header>

    <section id="about">
        <div class="container">


            <div class="row">

                <div class="col-sm-6 wow fadeInRight">
                <br><br><br><br><br><br>
                    <h3 class="column-title">{{message}}</h3>
                    {% if info %}
                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-3">
                            <p>Имя :</p>
                            <p>Email :</p>
                            <p>Номер телефона :</p>
                        </div>
                        <div class="col-md-5">
                            <p>{{info.name}}</p>
                            <p>{{info.email}}</p>
                            <p>{{info.telephone}}</p>
                        </div>
                    </div> 
                    <br><br><br>
                    {% endif %}  

                </div>
                <div class="col-sm-6 wow fadeInLeft">
                    {% if info %}
                    <img class="img-responsive" src="{% static 'images/success.png' %}" alt="">
                    {% else %}
                    <img class="img-responsive" src="{% static 'images/i_do_not_know.png' %}" alt="">
                    {% endif %}
                </div>
            </div>
        </div>
    </section><!--/#about-->

    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <p class="text-center">
                        &copy; 2015 iLost.kg </a>
                    </p>
                    <p style="display:none">
                        Ari and JZ)
                    </p>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/mousescroll.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/jquery.isotope.min.js' %}"></script>
    <script src="{% static 'js/jquery.inview.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    
</body>
</html>

main/templates/main/thanks_page.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>iLost.Kg</title>
	<!-- core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css'%}'%}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/animate.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/owl.carousel.css'%}" rel="stylesheet">
    <link href="{% static 'css/owl.transitions.css'%}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css'%}" rel="stylesheet">
    <link href="{% static 'css/main.css'%}" rel="stylesheet">
    <link href="{% static 'css/responsive.css'%}" rel="stylesheet">



   
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">


</head><!--/head-->
<body id="home" class="homepage">


    <header id="top-header" class="navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <!-- responsive nav button -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- /responsive nav button -->
                    
                    <!-- logo -->
                    <div>
                        <a href="{% url 'main:main'%}" >
                            <h4 style="color:white; font-size:24px;"><span style="color:red">i</span>Lost.Kg</h4>
                        </a>
                    </div>
                    <!-- /logo -->
                </div>

                <!-- main nav -->
                <nav class="collapse navbar-collapse navbar-right" role="navigation">
                    <div >
                        <ul id="nav" class="nav navbar-nav">
                            <li class="scroll"><a href="{%url 'main:main'%}#about" data-section="#about">О нас</a></li>
                            <li class="scroll"><a href="{%url 'main:main'%}#portfolio" data-section="#portfolio">Как это работает</a></li>
                            <li class="scroll"><a href="{%url 'main:main'%}#contact-area" data-section="#contact-area">Обратная связь</a></li>   
                        </ul>
                    </div>
                </nav>
                <!-- /main nav -->
            
                
            </div>
        </header>
   
    

    <section id="about">
        <div class="container">

            <div class="row">
                <div class="col-sm-6 wow fadeInRight">
                <br><br><br><br><br><br><br>
                <div class="alert alert-success alert-dismissible fade in" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                  <h3 class="column-title">{{message}}</h3>
                </div>
                    
                </div>
                <div class="col-sm-6 wow fadeInLeft">
                    <img class="img-responsive" src="{% static 'images/success.png' %}" alt="">
                </div>
            </div>
        </div>
    </section><!--/#about-->

    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <p class="text-center">
                        &copy; 2015 iLost.kg </a>
                    </p>
                    <p style="display:none">
                        Ari and JZ)
                    </p>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/mousescroll.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/jquery.isotope.min.js' %}"></script>
    <script src="{% static 'js/jquery.inview.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>


</body>
</html>